### ISSUE TITLE
Avoid building the image twice in docker-publish.yml

### ISSUE THREAD

**Issue by larseggert** [larseggert/i-d-toolchain#1]
There must be a way to do this by caching stuff, but my GitHub-Actions-fu isn't strong enough.

**Comment by martinthomson** [comment]
I use the [docker/build-push-action@v2](https://github.com/docker/build-push-action/) action for pushing.  That doesn't necessarily give you what you want directly, but you could try that with `push: false` and `load: true`.  That makes the image available for testing in the next step.  Then you can run your tests, followed by `docker push $tag` after that.

**Comment by larseggert** [comment]
I'm playing around with this in #7, but without much success so far.
